---
title: "plot_graphs"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{plot_graphs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(vivax)
```

This document shows how to interpret the output from the p. vivax model.

You can run the default model and store the output like so:

```{r}
output <- run_simulation(
  prev_min_ages = c(0, 2),
  prev_max_ages = c(5, 10),
  incidence_min_ages = c(0, 2),
  incidence_max_ages = c(5, 10)
)
```

Let's define some variables:

```{r}
# The number of mosquitos
N_spec = 3

# The names of the mosquito states
mosq_comp = c("EL_M_far", "LL_M_far", "P_M_far", "S_M_far", "E_M_far", "I_M_far",
        "EL_M_pun", "LL_M_pun", "P_M_pun", "S_M_pun", "E_M_pun", "I_M_pun",
                "EL_M_kol", "LL_M_kol", "P_M_kol", "S_M_kol", "E_M_kol", "I_M_kol")
```

## Human dynamics

```{r}

  plot(x=output$time/365, y=output$S, type='l',
  xlab="time (years)", ylab="number", main="S")

  plot(x=output$time/365, y=output$I_PCR, type='l',
  xlab="time (years)", ylab="number", main="I_PCR")

  plot(x=output$time/365, y=output$I_LM, type='l',
  xlab="time (years)", ylab="number", main="I_LM")

  plot(x=output$time/365, y=output$D, type='l',
  xlab="time (years)", ylab="number", main="D")

  plot(x=output$time/365, y=output$T, type='l',
  xlab="time (years)", ylab="number", main="T")

  plot(x=output$time/365, y=output$P, type='l',
  xlab="time (years)", ylab="number", main="P")
```

## Mosquito dynamics

```{r}

  for(g in 1:N_spec)
  {
    plot(x=output$time/365, y=output[[mosq_comp[1+(g-1)*6]]], type='l',
    xlab="time (years)", ylab="number", main=mosq_comp[1+(g-1)*6])

    plot(x=output$time/365, y=output[[mosq_comp[2+(g-1)*6]]], type='l',
    xlab="time (years)", ylab="number", main=mosq_comp[2+(g-1)*6])

    plot(x=output$time/365, y=output[[mosq_comp[3+(g-1)*6]]], type='l',
    xlab="time (years)", ylab="number", main=mosq_comp[3+(g-1)*6])

    plot(x=output$time/365, y=output[[mosq_comp[4+(g-1)*6]]], type='l',
    xlab="time (years)", ylab="number", main=mosq_comp[4+(g-1)*6])

    plot(x=output$time/365, y=output[[mosq_comp[5+(g-1)*6]]], type='l',
    xlab="time (years)", ylab="number", main=mosq_comp[5+(g-1)*6])

    plot(x=output$time/365, y=output[[mosq_comp[6+(g-1)*6]]], type='l',
    xlab="time (years)", ylab="number", main=mosq_comp[6+(g-1)*6])
  }
```

## Prevalence

```{r}

  #############################
  ## PANEL 1: PCR prevalence

  plot(x=output$time/365, y=output$PvPR_PCR/output$N_pop, type='l', ylim=c(0,0.6),
  xlab="time (years)", ylab="prevalence", main="Prevalence by PCR")

  points(x=output$time/365, y=output$PvPR_PCR_2_10/output$N_pop_2_10, type='l', col="orange")

  points(x=output$time/365, y=output$PvPR_PCR_0_5/output$N_pop_0_5, type='l', col="red")


  #############################
  ## PANEL 2: LM prevalence

  plot(x=output$time/365, y=output$PvPR_LM/output$N_pop, type='l', ylim=c(0,0.2),
  xlab="time (years)", ylab="prevalence", main="Prevalence by LM")

  points(x=output$time/365, y=output$PvPR_LM_2_10/output$N_pop_2_10, type='l', col="orange")

  points(x=output$time/365, y=output$PvPR_LM_0_5/output$N_pop_0_5, type='l', col="red")


  #############################
  ## PANEL 3: Clinical incdience

  plot(x=output$time/365, y=output$Pv_clin/output$N_pop, type='l', ylim=c(0,0.05),
  xlab="time (years)", ylab="prevalence", main="Prevalence of clinical disease")

  points(x=output$time/365, y=output$Pv_clin_2_10/output$N_pop_2_10, type='l', col="orange")

  points(x=output$time/365, y=output$Pv_clin_0_5/output$N_pop_0_5, type='l', col="red")


  #############################
  ## PANEL 4: EIR


  plot(x=output$time/365, y=365*output$EIR, type='l', 
  xlab="time (years)", ylab="EIR (ibppy)", main="EIR")


  #############################
  ## PANEL 5: Hypnozoite prevalence


  plot(x=output$time/365, y=output$PvHR/output$N_pop, type='l', ylim=c(0,1),
  xlab="time (years)", ylab="prevalence", main="Prevalence of hypnozoites")

  points(x=output$time/365, y=output$PvHR_2_10/output$N_pop_2_10, type='l', col="orange")

  points(x=output$time/365, y=output$PvHR_0_5/output$N_pop_0_5, type='l', col="red")


  #############################
  ## PANEL 6: Hypnozoite broods

  plot(x=output$time/365, y=output$PvHR_batch/output$N_pop, type='l', ylim=c(0,max(output$PvHR_batch/output$N_pop)),
  xlab="time (years)", ylab="", main="Mean number of hypnozoite batches per person")

  points(x=output$time/365, y=output$PvHR_batch_2_10/output$N_pop_2_10, type='l', col="orange")

  points(x=output$time/365, y=output$PvHR_batch_0_5/output$N_pop_0_5, type='l', col="red")
```

## Immunity
```{r}
  plot(x=output$time/365, y=output$A_par, type='l', col="blue",
  ylim=c(0,max(output$A_par, output$A_clin) ),
  xlab="time (years)", ylab="immunity", main="Anti-parasite & clinical immunity")

  points(x=output$time/365, y=output$A_clin, type='l', col="orange")
```
