# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Entrypoint for the simulation
#' 
#' @param model_param_path, the path of the model parameter file
#' @param mosq_param_paths, a list of paths to the mosquito parameter files.
#' The simulation requires 3 to run
#' @param coverage_param_path, the path of the coverage parameter file
#' @export
run_simulation_from_path <- function(model_param_path, fara_param_path, punc_param_path, koli_param_path, coverage_param_path, output_path) {
    .Call(`_vivax_run_simulation_from_path`, model_param_path, fara_param_path, punc_param_path, koli_param_path, coverage_param_path, output_path)
}

