# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Entrypoint for the simulation
#' 
#' @param model_param_path, the path of the model parameter file
#' @param fara_param_path, the path to the farauti mosquito parameter files.
#' @param punc_param_path, the path to the punctulatus mosquito parameter files.
#' @param koli_param_path, the path to the koliensis mosquito parameter files.
#' @param coverage_param_path, the path of the coverage parameter file
#' @param output_path, the path to write the results to
#' @param output_path, the path to write the results to
run_simulation_from_path <- function(model_param_path, fara_param_path, punc_param_path, koli_param_path, coverage_param_path, output_path) {
    .Call(`_vivax_run_simulation_from_path`, model_param_path, fara_param_path, punc_param_path, koli_param_path, coverage_param_path, output_path)
}

